# Generated by Django 2.2.3 on 2021-04-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_announcement_floor_photo_rooms_streets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='announcements',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Streets',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
