# Generated by Django 2.2.3 on 2021-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('administrator', '0003_auto_20210414_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='householder',
            name='add',
            field=models.ManyToManyField(blank=True, related_name='announcement_add', to='search.Announcement'),
        ),
    ]
