# Generated by Django 2.2.3 on 2021-04-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_householder_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='householder',
            old_name='add',
            new_name='addd',
        ),
    ]
