# Generated by Django 2.2.3 on 2021-04-17 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='geolocaion',
            field=models.CharField(default=datetime.datetime(2021, 4, 17, 16, 11, 36, 80001, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
